name: flutter-web-deploy

on:
  push:
    branches:
      - main # mainブランチへのpushをトリガーにする

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Actionsの実行環境

    steps:
      - uses: actions/checkout@v3 # リポジトリをチェックアウト
      - uses: actions/setup-java@v3 # Javaセットアップ (Flutterビルドに必要)
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2 # Flutterアクション
        with:
          flutter-version: '3.x' # 使用するFlutterバージョン (適宜変更)
          channel: 'stable'
      - run: flutter config --enable-web # ウェブを有効化
      - run: flutter pub get # パッケージ取得
      - run: flutter build web # ウェブビルド
      - uses: peaceiris/actions-gh-pages@v3 # GitHub Pagesデプロイアクション
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web # ビルド成果物のディレクトリ